Repository liuderchi/atom-i18n, pull requests merged in 2018-03, with the labels that each got.

#152 Fi
  def/fi/about.cson
  def/fi/context.cson
  def/fi/menu_darwin.cson
  def/fi/menu_linux.cson
  def/fi/menu_win32.cson
  def/fi/settings.cson
  def/fi/welcome.cson
  package.json
  spec/locales.js
Labels: i18n fi

#155 fix French translation of pane:close
  def/fr/context.cson
Labels: i18n fr

#164 Fix issue #156 (No checkbox at welcome screen)
  lib/welcome.js
Labels: : fix, under-review

#160 Polish translation update
  def/pl/settings.cson
Labels: i18n pl, under-review

#162 Issue 157
  def/ar/context.cson
  def/de/context.cson
  def/es/context.cson
  def/fi/context.cson
  def/fr/context.cson
  def/hi/context.cson
  def/hu/context.cson
  def/it/context.cson
  def/ja/context.cson
  def/ko/context.cson
  def/nl/context.cson
  def/pl/context.cson
  def/pt-br/context.cson
  def/ru/context.cson
  def/template/context.cson
  def/th/context.cson
  def/zh-cn/context.cson
  def/zh-tw/context.cson
Labels: : fix, under-review

#165 Add new Japanese translations
  def/ar/menu_win32.cson
  def/de/menu_win32.cson
  def/es/menu_win32.cson
  def/fi/menu_win32.cson
  def/fr/menu_win32.cson
  def/hi/menu_win32.cson
  def/hu/menu_win32.cson
  def/it/menu_win32.cson
  def/ja/menu_win32.cson
  def/ko/menu_win32.cson
  def/nl/menu_win32.cson
  def/pl/menu_win32.cson
  def/pt-br/menu_win32.cson
  def/ru/menu_win32.cson
  def/template/menu_win32.cson
  def/th/menu_win32.cson
  def/zh-cn/menu_win32.cson
  def/zh-tw/menu_win32.cson
Labels: i18n ja

#167 test(menu): do not use bracket for hotkey prompt in template
  def/template/menu_linux.cson
  def/template/menu_win32.cson
Labels: : test, enhancement, in progress
